### PR TITLE
Added documentation for array-splice() method along with its examples (Fixes #43)

### LINKED ISSUE #43: New Function: Array splice()
## What
Add new method documentation file for a new JavaScript function in `src/content/docs`.
The instructions about defining the file's name are documented in the `CONTRIBUTING.md` file.

## Description
Function name: example `Array.splice()`
Function description: changes the content of an array, adding, replacing or removing elements
File name: example `02-array/13_array-splice.md`

## Checklist
- [ ] create the file with the proper name
- [ ] create the documentation of the function
- [ ] write example in `examples` directory
- [ ] execute `bun run format-examples-bun` or `npm run format-examples`
- [ ] commit and open the PR.

Must read:

- https://github.com/roberto-butti/some-drops-of-javascript/blob/main/HACKTOBERFEST.md
- https://github.com/roberto-butti/some-drops-of-javascript/blob/main/CONTRIBUTING.md

### PR DESCRIPTION
**Pull request by wdym69**
Tasks done:
- Added documentation for `splice()` method
- Added examples for `splice()` method

### CODE REVIEW

**Comment by roberto-butti** [comment]
Amazing, thank you @wdym69 .
I appreciate all your effort.

If I can provide some suggestions:
- I see you pushed all the examples with formatting options from a new Prettier version. This is fine, but eventually, it is better to raise a specific PR.
- I would like to have four sections (second-level title), with an Introduction where you can explain an overview of the splice command and then three main use cases, such as adding items, removing items, and replacing items.

What do you think?
If you agree with the feedback and want, you can push an additional commit. Otherwise, I can start merging the PR, and eventually, I can review it and raise an additional PR.

Let me know.

**Comment by wdym69** [comment]
Thankyou for the suggestions @roberto-butti . I agree with the feedback and will push another commit soon.

Edit: I will raise a new PR

**Comment by wdym69** [comment]
i have a doubt:

what version of prettier are we using here? as we use `npx prettier ./examples/ --write` and don't specifically mention the prettier version it automatically uses the latest version. 
so should i raise two different PR's? one for `Array.splice()` documentation and other for examples as it uses latest prettier version (as suggested)
Please help!

**Comment by roberto-butti** [comment]
hi @wdym69 , you can use the latest version of prettier.
 
the latest one introduces a lot of code style fixes. so is better in my opinion to raise 2 PRs , one with the code style fixes on the examples directory, and another one ( PR ) for splice documentation and example.

**Pull request closed without merging**
