### PR TITLE
#1 Issue Fixed : Added Prettier as Dev Dependency

### PR DESCRIPTION
**Pull request by dushyantpant5**
-> Added Prettier package as devDependencies
-> Use `npx prettier ./examples/ --write` or` npm prettier ./examples/ --write` 
-> Formatted existing files inside /examples

### CODE REVIEW

**Comment by mahesha1150** [comment]
For npx prettier ./examples/ --write to work, prettier dependency should be added under devDependencies as below: Please check

"devDependencies": {
"bun-types": "^1.0.3",
"prettier": "^3.0.3"
},

**Comment by roberto-butti** [comment]
> For npx prettier ./examples/ --write to work, prettier dependency should be added under devDependencies as below: Please check
> 
> "devDependencies": { "bun-types": "^1.0.3", "prettier": "^3.0.3" },

Usually, i include prettier as devdependencies (this is why i created the issue, including the info for installing prettier as devdependency). 
But I see in the scripts section prettier is launched via npx, so it is not needed as a dependency.

**Comment by roberto-butti** [comment]
> -> Added Prettier package as devDependencies -> Use `npx prettier ./examples/ --write` or` npm prettier ./examples/ --write` -> Formatted existing files inside /examples

Thank you for this PR @dushyantpant5 .
I have a question for you, what do you think if, for the `.prettierrc` file, we can set some default values like:
```
 {
   "trailingComma": "es5",
   "tabWidth": 4,
   "semi": false,
   "singleQuote": true
 }
```

**Comment by dushyantpant5** [comment]
@roberto-butti  If you want to add these rules , then I can make the changes. Please let me know.
Also if there is any other thing to do.

**Comment by roberto-butti** [comment]
> @roberto-butti If you want to add these rules , then I can make the changes. Please let me know. Also if there is any other thing to do.

Yes please @dushyantpant5  , set the .prettierrc . So, once we have some basic rules, in the future we can perform some fine tuning.

**Comment by dushyantpant5** [comment]
@roberto-butti  Updated the rules on prettier

**Review by roberto-butti — APPROVED** [review]

**Comment by roberto-butti** [comment]
> @roberto-butti Updated the rules on prettier

Amazing! thank you for the contribution!

**Pull request merged**
