### PR TITLE
Added explanation for the slice() function in JavaScript

### PR DESCRIPTION
**Pull request by Abd-Elhadi**
This PR adds an explanation of the slice() method, including syntax, examples, and key points.

### CODE REVIEW

**Comment by roberto-butti** [comment]
Thank you @Abd-Elhadi great PR,
I want to merge it, Can you change the filename to 14_array-slice.md (i see you used 13, but 13 is for splice that is a work in progress.) 
Thank you

**Comment by Abd-Elhadi** [comment]
Hi @roberto-butti ,

I've renamed the file to 14_array-slice.md.

Thanks for pointing that out!

**Comment by roberto-butti** [comment]
Thank you @Abd-Elhadi very fast :)
I 'm going to merge it

**Comment by Abd-Elhadi** [comment]
You're welcome! Glad I could help quickly! 😄

**Pull request merged**
