### PR TITLE
feat: add copyWithin method documentation and example

### PR DESCRIPTION
**Pull request by DomeT99**
- This PR is for issue #61.
- It includes a new markdown file explaining the method and its usage, as well as an example file demonstrating use case.

### CODE REVIEW

**Comment by roberto-butti** [comment]
Thank you @DomeT99 
I believe that `copyWithin` is a challenging function in JavaScript arrays. To make it more accessible, I recommend providing additional examples with clear explanations and comments highlighting the expected output of each scenario, including any console.log statements.

You can start with a very basic example with just one parameter and then covering example for all the three parameters.

IF you have time and want to do it, feel free to do it. If you don't want, it is fine as well, i can merge this PR and eventually i can review it.
Thank you for your PR :)

**Comment by DomeT99** [comment]
You're right, `copyWithin` can be employed in multiple ways. I will provide other examples without problems and detail.

**Comment by DomeT99** [comment]
I fixed the documentation and added a lot more details. 
For anything I remain available :rocket:

**Comment by roberto-butti** [comment]
Thank you, @DomeT99 , I'm going to merge the PR. Welcome as a contributor :)

**Pull request merged**
