### PR TITLE
Added examples and documentation of the array at() method.

### PR DESCRIPTION
**Pull request by seferovich**
Created the documentation for the at() method based on the CONTRIBUTING.md guide. Issue #54

### CODE REVIEW

**Comment by seferovich** [comment]
I changed the name from `15_array-at.md` to  `16_array-at.md`, because someone did a pr before me and used `15` already.

**Comment by roberto-butti** [comment]
Hello than you for your PR.
I'm going to review it.
Please the name of the file is : 02-array/17_array-at.md as mentioned in the issue #54

**Comment by seferovich** [comment]
Fixed it, I thought that it was just an example and not how I should name it, sorry for that.

**Comment by roberto-butti** [comment]
Thank you for the PR, and thank you for accommodating the requests.
I'm going to merge this helpful PR.

**Pull request merged**
