### PR TITLE
feat: add entries method documentation and example

### PR DESCRIPTION
**Pull request by DomeT99**
- This PR is for issue #72 
- It includes a new markdown file explaining the method and its usage, as well as an example file demonstrating use case.

If there are any problems, I remain available :)

### CODE REVIEW

**Comment by roberto-butti** [comment]
Hi @DomeT99 this is a great PR. Thank you for your time and commitment.
I'll give you a suggestion. Let's see if you agree.
I know we are in the array section, but in this explanation, i would like to mention that `entries()` is available for Object and Map adding a brief explanation and a short example (one for Object and one for Map).
Thank you!

**Comment by DomeT99** [comment]
Hi @roberto-butti 
It's a good idea!
You could mention that `entries()` is a method of both Map and Object with a small example and then insert a link to the page specific for more information.
Let me know :)

**Comment by roberto-butti** [comment]
@DomeT99 do you want to add it as part of this PR?

**Comment by DomeT99** [comment]
No problems.

**Comment by roberto-butti** [comment]
Thank you @DomeT99  for the PR and for your addings.
Magical

I'm going to merge it

**Pull request merged**
