### PR TITLE
Added property description for path.sep  #7

### PR DESCRIPTION
**Pull request by mahesha1150**
Hi @roberto-butti, Please review the PR for #7. Let me know if there is anything I am missing. Thanks.

### CODE REVIEW

**Comment by roberto-butti** [comment]
> Hi @roberto-butti, Please review the PR for #7. Let me know if there is anything I am missing. Thanks.

Thank you @mahesha1150 for your contribution. Your PR is great.
You provided context and explained why the `path.sep` is important.
Also, the example you provided is good.If you want, you can add an additional example in the article combining the join function like:

```
const path = require('path');

const folderName = 'documents';
const fileName = 'file.txt';
console.log(['user', folderName, fileName].join(path.sep))
```

**Comment by mahesha1150** [comment]
> > Hi @roberto-butti, Please review the PR for #7. Let me know if there is anything I am missing. Thanks.
> 
> Thank you @mahesha1150 for your contribution. Your PR is great. You provided context and explained why the `path.sep` is important. Also, the example you provided is good.If you want, you can add an additional example in the article combining the join function like:
> 
> ```
> const path = require('path');
> 
> const folderName = 'documents';
> const fileName = 'file.txt';
> console.log(['user', folderName, fileName].join(path.sep))
> ```

**Comment by mahesha1150** [comment]
Thanks for the feedback. Please check if below lines are fine. I can create another PR with below changes.

//Another example of creating filePath using path.sep along with join function
console.log(['user', folderName, fileName].join(path.sep))

**Comment by mahesha1150** [comment]
Have added the example as suggested @roberto-butti.

**Comment by roberto-butti** [comment]
This is amazing , I'm going to merge your PR for "Some drops of JavaScript" :)
Thank you for the support and the high quality of the contribution.

**Comment by roberto-butti** [comment]
@mahesha1150 your creation: https://drops-of-javascript.hi-folks.dev/03-var/02_path-sep/

**Pull request merged**
